Models/ErrorViewModel.cs
using System;

namespace nlidbclient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/GeneralController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;
using System.Linq;


namespace nlidbclient.Controllers
{


    [Route("api/[controller]")]
    public class GeneralController : ControllerBase
    {

        private const string constr = "Server=IN-L20053\\MSSQLSERVER17;Initial Catalog=HACKITSM;Persist Security Info=False;User ID=sa;Password=Password@123;MultipleActiveResultSets=False;Connection Timeout=30;";// ConfigurationManager.ConnectionStrings["ConString"].ConnectionString;


        [HttpGet]
        public List<string> GetSuggetion()
        {
            string sql = "Select  Distinct Text From Generated_Sql";
            DataSet ds = DBHelper.GetDataFromDB(sql);

            List<string> list = new List<string>();
            if(ds!= null && ds.Tables.Count >0)
            {
                foreach(DataRow row in ds.Tables[0].Rows)
                {
                    list.Add(row[0].ToString());
                }
            }
            return list;
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using nlidbclient.Models;

namespace nlidbclient.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NLIDBController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using nlidbclient.Models;

namespace nlidbclient.Controllers
{
    public class IIEModel{

        public IIEModel()
        {
            Text="";
            Table = new DataTable();
        }
        public string Text{get;set;}
        public DataTable Table{get;set;}
    }
    public class NLIDBController : Controller
    {
        [HttpPost]
        public ActionResult CreateQuery(string query)
        {
            var data = new NLPQuery()
            {
                Text = query// "what is Symptom and CategoryName for all Incident whose ID is 1",
            };

            string URL = "http://localhost:5000/query";
            var client = new HttpClient();

            var myContent = JsonConvert.SerializeObject(data);
            var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
            var byteContent = new ByteArrayContent(buffer);
            byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            DataTable dt = new DataTable();
            try
            {
                var response = client.PostAsync(URL, byteContent).Result;

                if (response.IsSuccessStatusCode)
                {
                    var contents = response.Content.ReadAsStringAsync().Result;
                    DataSet ds = DBHelper.GetDataFromDB(contents);
                    dt = ds.Tables[0];
                    if (dt.Rows.Count > 0)
                        DBHelper.SaveSqlQuery(query, contents);
                    else
                        ErrorMessage(dt);
                }
                else
                {
                    ErrorMessage(dt);
                }
            }
            catch (Exception ex)
            {
                ErrorMessage(dt);
            }
            IIEModel model = new IIEModel()
            {
                Text = query,
                Table = dt
            };
            return View("Client", model);
        }

        private void ErrorMessage(DataTable dt)
        {
            dt.Clear();
            dt.Columns.Clear();
            dt.Columns.Add("INFO:");
            DataRow row = dt.NewRow();
            row[0] = "Our database does not contain the information you are seeking.";
            dt.Rows.Add(row);
        }

        public IActionResult Client()
        {
            ViewData["Message"] = "Client";
            IIEModel model = new IIEModel();
            return View(model);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/NLIDB/Client.cshtml
@using System.Data
@using nlidbclient.Controllers
@model IIEModel
@{
    ViewData["Title"] = "Demo Client";
}
<br>
<div class="row">
    @using(Html.BeginForm("CreateQuery","NLIDB"))
    {
        <div class="row">
            <div class="col-md-8">
                <div class="dropdown">
                    <input type="text" id="txtQuery" autocomplete="off" name="query"  class="form-control" placeholder="type query" style="width:100%" data-provide="typeahead" value="@Model.Text">
                </div>
            </div>
            <div>
               <input type="submit" class="btn btn-success" />
            </div>
        </div>
    }
    <div class="col-md-4"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-12" style="height:750px">
        @if(Model.Table.Rows.Count>0)
        {
        
            <table class="table" cellpadding="0" cellspacing="0">
                <tr>
                    @foreach (DataColumn column in Model.Table.Columns )
                    {
                        <th>@column.ColumnName</th>
                    }
                </tr>
                @foreach (DataRow row in Model.Table.Rows)
                {
                    <tr>
                        @foreach (DataColumn column in Model.Table.Columns )
                        {
                            <td>@row[column.ColumnName]</td>
                        }
                    </tr>
                }
            </table>
        }
    </div>
</div>



@section Scripts
{
    <script>

    //  function(query) {
    //         return $.get("http://localhost:5001/api/general?prefix="+query);
    //         }
       var jsonData = ["Naveen","Sharma","Sachin","Nirav"];

    var productNames = [];
    $.each(jsonData, function(index, product) {
      productNames.push(product.name + "#" + product.image + "#" + product.id);
    });

    $.get("http://localhost:5001/api/general", function(data){
       // $("#name").typeahead({ source:data });
   

    $('#txtQuery').typeahead({
      source: data,
      highlighter: function(item) {
        //var parts = item.split('#'),
          html = '<div><div class="typeahead-inner" >';
        // html += '<div class="item-img" style="background-image: url(' + parts[1] + ')"></div>';
        html += '<div class="item-body">';
        html += '<p class="item-heading">' +item + '</p>';
        html += '</div>';
        html += '</div></div>';

        var query = this.query;
        var reEscQuery = query.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
        var reQuery = new RegExp('(' + reEscQuery + ')', "gi");
        var jElem = $(html);
        var textNodes = $(jElem.find('*')).add(jElem).contents().filter(function() {
          return this.nodeType === 3;
        });
        textNodes.replaceWith(function() {
          return $(this).text().replace(reQuery, '<strong>$1</strong>');
        });

        return jElem.html();
      },
      updater: function(selectedName) {
        var name = selectedName;
        return name;
      }
    });
 },'json');


    //  $( document ).ready(function() {
    //     $('#txtQuery').typeahead({
    //         name: 'search',
    //         remote: {
    //         url: 'http://suggestqueries.google.com/complete/search?client=chrome&q=%QUERY',
    //         dataType: 'jsonp',
    //         cache: false,
    //         filter: function(parsedResponse){
    //             return (parsedResponse.length > 1) ? parsedResponse[1] : [] ;
    //         }
    //         }
    //     }).on('typeahead:selected', function(e){
    //         e.target.form.submit();
    //     });
    //     });
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IIE</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <!-- <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" /> -->
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-ivanti navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 <ul><a asp-area="" asp-controller="NLIDB" asp-action="Client" class="navbar-brand">Intelligent Information Extractor</a></ul>
                <!-- <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">IIE</a> -->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li> -->
                     <!-- <li><a asp-area="" asp-controller="NLIDB" asp-action="Client">Client</a></li> -->
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - IIE</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.0/bootstrap3-typeahead.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>